apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: session-service
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: session-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: session-service
    spec:
      containers:
      - image: zoranashura402/session
        imagePullPolicy: IfNotPresent
        name: session-service
        envFrom:
          - configMapRef:
              name: session-config
          - configMapRef:
              name: general-config
          - secretRef:
              name: postgres-secret
        command: ["java", "-jar", "/app/app.jar"]
        ports:
        - containerPort: 8081

---
