apiVersion: v1
kind: ConfigMap
metadata:
  name: session-config
data:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
    #  POSTGRES_USER: postgres
    # POSTGRES_PASSWORD: postgres
  POSTGRES_DB: users_db
  
